worker_processes auto;

pid /tmp/nginx.pid;

events {}

http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;

    access_log /tmp/access.log;
    error_log  /tmp/error.log;

    server {
        listen 80;

        root /usr/share/nginx/html;
        index index.html;

        location /api/ {
            proxy_pass http://app-multicamada-backend-service:8080/;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}