# ── Service (ClusterIP) ────────────────────────────────────────────────────────
apiVersion: v1
kind: Service
metadata:
  name: app-multicamada-frontend-service
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
